"""Shopify operation contracts and the inert P05 compatibility boundary."""

from .gateway_facade import (
    FacadeMode,
    GatewayFacade,
    GatewayMode,
    ShopifyApiClientFacade,
    ShopifyClientFacade,
    ShopifyFacadeMode,
    ShopifyGatewayFacade,
)
from .graphql_executor import (
    CostMetadata,
    ExecutorError,
    GraphQLError,
    GraphQLExecutor,
    GraphQLExecutorError,
    GraphQLResult,
    GraphQLThrottleStatus,
    GraphQLUserError,
    ShopifyGraphQLExecutionError,
    ShopifyExecutor,
    ShopifyExecutorError,
    ThrottleStatus,
)
from .transport import (
    ShopifyTransport,
    ShopifyTransportError,
    ShopifyTransportErrorCode,
    ShopifyTransportRequest,
)

from .operation_registry import (
    OperationIdentity,
    ReadbackMetadata,
    ShopifyOperationRegistry,
    ShopifyOperationSpec,
    SideEffectMetadata,
)
from .read_comparison import (
    DEFAULT_SAMPLE_MODULUS,
    MAX_SAMPLE_MODULUS,
    REPLAY_SAFE_READ_OPERATIONS,
    ReadComparisonEvidence,
    compare_values,
    safe_digest,
    should_compare,
)
from .read_contracts import (
    CursorProgress,
    LocationDTO,
    MoneyDTO,
    ReadCompatibilityAdapter,
    ReadGatewayError,
    ReadGatewayMode,
    ReadObservation,
    ReadOperation,
    ReadPage,
    ReadResult,
    ReadShapeError,
    SHOPIFY_API_VERSION as READ_SHOPIFY_API_VERSION,
    StoreCapabilityDTO,
    StoreIdentityDTO,
    myshopify_domain,
    page_from_connection,
    response_data,
    shopify_cursor,
    shopify_gid,
)
from .read_gateway import (
    LOCATION_PAGE_OPERATION,
    STORE_CAPABILITY_OPERATION,
    LocationReadGateway,
    StoreCapabilityReadGateway,
)

__all__ = [
    "CostMetadata",
    "ExecutorError",
    "FacadeMode",
    "GatewayFacade",
    "GatewayMode",
    "GraphQLError",
    "GraphQLExecutor",
    "GraphQLExecutorError",
    "GraphQLResult",
    "GraphQLThrottleStatus",
    "GraphQLUserError",
    "OperationIdentity",
    "ReadbackMetadata",
    "ShopifyOperationRegistry",
    "ShopifyOperationSpec",
    "ShopifyApiClientFacade",
    "ShopifyClientFacade",
    "ShopifyFacadeMode",
    "ShopifyGatewayFacade",
    "ShopifyGraphQLExecutionError",
    "ShopifyExecutor",
    "ShopifyExecutorError",
    "ShopifyTransport",
    "ShopifyTransportError",
    "ShopifyTransportErrorCode",
    "ShopifyTransportRequest",
    "SideEffectMetadata",
    "ThrottleStatus",
    "CursorProgress",
    "LocationDTO",
    "MoneyDTO",
    "ReadCompatibilityAdapter",
    "ReadGatewayError",
    "ReadGatewayMode",
    "ReadObservation",
    "ReadOperation",
    "ReadPage",
    "ReadResult",
    "ReadShapeError",
    "READ_SHOPIFY_API_VERSION",
    "StoreCapabilityDTO",
    "StoreIdentityDTO",
    "myshopify_domain",
    "page_from_connection",
    "response_data",
    "shopify_cursor",
    "shopify_gid",
    "DEFAULT_SAMPLE_MODULUS",
    "MAX_SAMPLE_MODULUS",
    "REPLAY_SAFE_READ_OPERATIONS",
    "ReadComparisonEvidence",
    "compare_values",
    "safe_digest",
    "should_compare",
    "LOCATION_PAGE_OPERATION",
    "STORE_CAPABILITY_OPERATION",
    "LocationReadGateway",
    "StoreCapabilityReadGateway",
]
