from . import misc
from . import marketplace_instance
from . import locations
from . import res_partner
from . import marketplace_listing
from . import marketplace_listing_item
from . import shopify_tags
from . import listing_image
from . import collections_condition
from . import collections_source
from . import collections
from . import shopify_collection_job
from . import shopify_payment_gateway
from . import shopify_order_status
from . import sale_order
from . import delivery
from . import marketplace_listing_image
from . import shopify_financial_workflow_config
from . import webhook
from . import marketplace_queue_job
from . import shopify_fraud_analysis
from . import product
from . import stock
from . import account_bank_statement
from . import payout
from . import shopify_payout_account_config
from . import shopify_payout_transaction_type
from . import logs
from . import account_move
from . import account_move_line
from . import order_workflow
from . import graphql_queries
from . import product_category
from . import shopify_product_type
from . import shopify_product_category
from . import shopify_sales_channels
from . import shopify_metafield_resource
from . import shopify_metafield_mapping
from . import shopify_metaobject_definition
from . import shopify_metaobject_field
from . import shopify_metaobject_entry
from . import shopify_metaobject_entry_value
from . import shopify_market
from . import shopify_catalog_validation
from . import shopify_catalog
from . import shopify_catalog_product
from . import shopify_return_line
from . import shopify_return
from . import shopify_return_reason
from . import shopify_bulk_query
