import logging

from odoo import models, fields, api, _, Command
from odoo.addons.base_marketplace.models.exceptions import MarketplaceException
from odoo.addons.shopify.models.graphql_queries import (FETCH_METAOBJECT_ENTRIES, GET_METAOBJECTS_BY_IDS,
                                                        CREATE_METAOBJECT, UPDATE_METAOBJECT, DELETE_METAOBJECT,
                                                        METAOBJECTS_BATCH_QUERY, METAOBJECT_BATCH_ALIAS)
from odoo.addons.shopify.models.misc import extract_numeric_id, exception_message

GID_CHUNK_SIZE = 100

DEFINITION_BATCH_SIZE = 10
BATCH_PAGE_SIZE = 50

_logger = logging.getLogger(__name__)


def _build_shopify_metaobjects_batch_query(count, first):
    """Task: T9096 - Assemble METAOBJECTS_BATCH_QUERY for a batch of `count` types.
    Only the assembly lives here - one alias per type, joined together - the GraphQL text
    itself (METAOBJECTS_BATCH_QUERY, METAOBJECT_BATCH_ALIAS) is in graphql_queries.py with
    every other query and mutation.
    Args:
        count (int): Number of types in this batch.
        first (int): Page size per type.
    Returns:
        str: The query document, with $type0..$type{count-1} to fill in as variables.
    """
    var_decls = ', '.join(f"$type{i}: String!" for i in range(count))
    aliases = "\n".join(METAOBJECT_BATCH_ALIAS % {'index': i, 'first': first} for i in range(count))
    return METAOBJECTS_BATCH_QUERY % {'var_decls': var_decls, 'aliases': aliases}


class ShopifyMetaobjectEntry(models.Model):
    """One Shopify metaobject entry (a "filled-in form").

    This is the model that product/variant/order/customer metaobject-reference
    metafields point at. It is the only metaobject model Odoo may create or
    write back to Shopify.
    """
    _name = 'shopify.metaobject.entry.ts'
    _description = 'Shopify Metaobject Entry'
    _order = 'definition_id, display_name_ts'
    _rec_name = 'display_name_ts'

    mk_instance_id = fields.Many2one('mk.instance', string="Instance", required=True, ondelete='cascade',
                                     help="Marketplace instance this entry belongs to.")
    definition_id = fields.Many2one('shopify.metaobject.definition.ts', string="Metaobject", required=True,
                                    ondelete='cascade', domain="[('mk_instance_id', '=', mk_instance_id)]",
                                    help="Metaobject definition this entry is an instance of.")
    shopify_type = fields.Char(related='definition_id.shopify_type', store=True, string="Type")
    is_app_writable = fields.Boolean(related='definition_id.is_app_writable', store=True,
                                     string="Writable by Apps")

    mk_id = fields.Char(string="Shopify ID", index=True, copy=False,
                        help="Numeric part of the Shopify Metaobject GID. Empty until the entry is pushed to Shopify. "
                             "This is the identity used to match entries, never the handle.")
    handle = fields.Char(string="Handle", copy=False,
                         help="Shopify handle of the entry. Generated by Shopify when omitted on create. "
                              "Used as the write key for metaobjectUpsert.")
    display_name_ts = fields.Char(string="Shopify Display Name", readonly=True, copy=False,
                                  help="Value of the definition's display name field. Computed by Shopify from the "
                                       "field named in the definition, so it is filled in on import or on push.")

    value_ids = fields.One2many('shopify.metaobject.entry.value.ts', 'entry_id', string="Values", copy=True,
                                help="One row per field of the definition.")

    _uniq_entry_per_instance = models.Constraint(
        "UNIQUE(mk_instance_id, definition_id, mk_id)",
        "This metaobject entry already exists for this instance.")

    def _shopify_entry_label(self):
        """Task: T9096 - Readable name for logs: Shopify display name, else handle, else the Odoo id."""
        self.ensure_one()
        return self.display_name_ts or self.handle or str(self.id)

    def _is_shopify_entry_referenced(self, with_usages=False):
        """Task: T9096 - True when some other Odoo record still points at this entry.

        Checks both the auto-created product/customer/... fields (see
        shopify.metafield.mapping.ts._create_shopify_metaobject_odoo_field) and nested
        metaobject_reference values held on other entries. Used to keep a manual or
        auto-cleanup delete from silently breaking a link the merchant still relies on.
        With with_usages=True it returns where the entry is used (first 5 per place, as
        readable text, empty when unused) instead of a bool, for log messages.
        """
        self.ensure_one()
        limit = 5 if with_usages else 1
        usages = []
        manual_fields = self.env['ir.model.fields'].sudo().search([
            ('relation', '=', self._name), ('state', '=', 'manual')])
        for field in manual_fields:
            model = self.env.get(field.model)
            if model is None or field.name not in model._fields:
                continue
            domain = [(field.name, 'in', self.ids)] if field.ttype == 'many2many' else [(field.name, '=', self.id)]
            records = model.sudo().search(domain, limit=limit)
            if records and not with_usages:
                return True
            usages += [f"{field.model_id.name}: {record.display_name}" for record in records]

        values = self.env['shopify.metaobject.entry.value.ts'].sudo().search(
            ['|', ('val_entry_id', '=', self.id), ('val_entry_ids', 'in', self.id)], limit=limit)
        if not with_usages:
            return bool(values)
        return usages + [_("Metaobject entry: %s") % value.entry_id._shopify_entry_label() for value in values]

    @api.model_create_multi
    def create(self, vals_list):
        """Task: T9096 - No entry can be added for an instance that has metaobjects turned off.

        Covers every way of adding one: Add Entry, New inside an entry picker, imports.
        """
        instances = self.env['mk.instance'].browse(
            [vals.get('mk_instance_id') or self.env.context.get('default_mk_instance_id') for vals in vals_list])
        disabled = instances.filtered(lambda instance: not instance.enable_metaobject)
        if disabled:
            raise MarketplaceException(_(
                "UPDATE METAOBJECT ENTRY: Cannot add an entry for instance (%(instance)s)\n"
                "Reason: Metaobject Functionality is turned off for this instance\n"
                "How to fix:\n"
                "  • Go to Marketplaces > Configuration > Instance, open the instance, go to the Metafields tab, and turn on Metaobject Functionality."
            ) % {'instance': ', '.join(disabled.mapped('name'))})
        return super().create(vals_list)

    def unlink(self):
        """Task: T9096 - Block removing an entry that something else in Odoo still points at.

        Applies to every deletion path - the standard list/form delete, the auto-cleanup
        below, and action_delete_from_shopify - since they all end up calling this.
        """
        for entry in self:
            usages = entry._is_shopify_entry_referenced(with_usages=True)
            if usages:
                raise MarketplaceException(_(
                    "SHOPIFY METAOBJECT: Cannot remove entry %(entry)s (%(definition)s)\n"
                    "Reason: it is still used by these records:\n"
                    "%(usages)s\n"
                    "How to fix:\n"
                    "  • Remove the entry from these records, then remove it again"
                ) % {'entry': entry._shopify_entry_label(), 'definition': entry.definition_id.name,
                     'usages': "\n".join(f"  • {usage}" for usage in usages)})
        return super().unlink()

    @api.onchange('definition_id')
    def _onchange_shopify_definition_id(self):
        """Task: T9096 - Generate one blank value row per field of the chosen definition."""
        for record in self:
            if not record.definition_id:
                record.value_ids = [Command.clear()]
                continue
            record.value_ids = [Command.clear()] + [
                Command.create({'field_id': field.id}) for field in record.definition_id.field_ids
            ]

    # ==================================================================
    # IMPORT
    # ==================================================================
    def import_shopify_metaobject_entries(self, definition):
        """Task: T9096 - Import every entry of a metaobject definition from Shopify.

        Args:
            definition (recordset): Recordset of shopify.metaobject.definition.ts.
        Returns:
            bool: True once the import finished (errors are logged, not raised).
        """
        mk_instance_id = definition.mk_instance_id
        if mk_instance_id.state != 'confirmed':
            raise MarketplaceException(_(
                "IMPORT METAOBJECT DEFINITION: Cannot fetch entries of metaobject %(definition)s\n"
                "Reason: instance (%(instance)s) is not confirmed\n"
                "How to fix:\n"
                "  • Confirm the instance, then click Fetch Entries again"
            ) % {'definition': definition.display_name, 'instance': mk_instance_id.name})

        # Nested inside another operation (Fetch Definitions) this writes into that operation's log;
        # on its own (Fetch Entries) it opens a new one and removes it again when it stays blank.
        mk_log_id = self.env.context.get('mk_log_id')
        new_log = not (mk_log_id and mk_log_id.exists())
        if new_log:
            mk_log_id = self.env['mk.log'].create_update_log(mk_instance_id=mk_instance_id, operation_type='import')
        self = self.with_context(mk_log_id=mk_log_id)
        mk_log_line_dict = {'error': [], 'success': []}
        received_mk_ids = set()
        is_complete = True
        try:
            mk_instance_id.connection_to_shopify()

            # Fetch Entries only fetches entry data by design, but a field added to this
            # definition in Shopify since the last Fetch Definitions would otherwise never
            # be noticed: an old entry with no value set for that field doesn't mention its
            # key at all in Shopify's response, so there is nothing in the entry data itself
            # to detect the gap from (unlike the on-demand nested-reference path, which
            # checks the values it does see - see _resolve_shopify_definitions_for_nodes). Refresh
            # the schema unconditionally here instead, exactly like action_fetch_shopify_metaobject_definitions
            # already does before it imports entries. Kept in its own try/except so a
            # definitions-fetch hiccup is reported as such and does not stop the entries
            # below from still being imported against the (possibly stale) existing schema.
            try:
                definition_obj = self.env['shopify.metaobject.definition.ts']
                fetched_definitions, _is_complete = definition_obj.with_context(
                    skip_metaobject_definition_auto_import=True,
                )._fetch_shopify_metaobject_definitions(mk_instance_id, mk_log_line_dict)
                if fetched_definitions:
                    definition_obj._create_or_update_shopify_metaobject_definitions(fetched_definitions, mk_instance_id)
            except Exception as e:
                mk_log_line_dict['error'].append({'log_message': _(
                    "IMPORT METAOBJECT ENTRY: Could not refresh the fields of metaobject %(definition)s before fetching its entries\n"
                    "Reason: %(error)s (the entries were still fetched with the fields Odoo already has)\n"
                    "How to fix:\n"
                    "  • Click Fetch Definitions to refresh the fields"
                ) % {'definition': definition.display_name, 'error': exception_message(e)}})

            cursor = None
            while True:
                variables = {"type": definition.shopify_type, "first": 250, "metaobjectCursor": cursor}
                res = mk_instance_id.execute_graphql_query(FETCH_METAOBJECT_ENTRIES, variables=variables)
                if res and res.get('errors'):
                    mk_log_line_dict['error'].append({'log_message': _(
                        "IMPORT METAOBJECT ENTRY: Could not fetch entries of metaobject %(definition)s from Shopify\n"
                        "Reason: Shopify returned an error: %(error)s"
                    ) % {'definition': definition.display_name, 'error': res.get('errors')}})
                    is_complete = False
                    break
                data = ((res or {}).get('data') or {}).get('metaobjects') or {}
                nodes = data.get('nodes') or []
                for node in nodes:
                    gid = node.get('id')
                    if gid:
                        received_mk_ids.add(str(extract_numeric_id(gid)))
                if nodes:
                    self._create_or_update_shopify_metaobject_entries(nodes, mk_instance_id, mk_log_line_dict)
                page_info = data.get('pageInfo') or {}
                if not page_info.get('hasNextPage'):
                    break
                cursor = page_info.get('endCursor')
        except Exception as e:
            is_complete = False
            mk_log_line_dict['error'].append({'log_message': _(
                "IMPORT METAOBJECT ENTRY: Failed to fetch entries of metaobject %(definition)s\n"
                "Reason: %(error)s"
            ) % {'definition': definition.display_name, 'error': exception_message(e)}})

        # Only clean up on a fetch that saw every page: a partial fetch must never be read
        # as "these entries are gone", or a rate-limit hiccup would delete real data.
        if is_complete:
            self._cleanup_stale_shopify_entries(definition, mk_instance_id, received_mk_ids, mk_log_line_dict)

        self.env['mk.log'].create_update_log(mk_log_id=mk_log_id, mk_instance_id=mk_instance_id,
                                             operation_type='import', mk_log_line_dict=mk_log_line_dict)
        if new_log and not mk_log_id.log_line_ids:
            mk_log_id.unlink()
        return True

    def _cleanup_stale_shopify_entries(self, definition, mk_instance_id, received_mk_ids, mk_log_line_dict):
        """Task: T9096 - Remove entries that no longer exist in Shopify, after a complete fetch.

        Only entries that were actually pushed (mk_id set) are considered - a local draft
        the merchant is still filling in is never touched by this. An entry still
        referenced elsewhere in Odoo is kept and reported instead of being removed, per
        the guard in unlink().

        Args:
            definition (recordset): Recordset of shopify.metaobject.definition.ts.
            mk_instance_id (recordset): Recordset of mk.instance.
            received_mk_ids (set): Shopify ids seen in this fetch.
            mk_log_line_dict (dict): Dictionary to collect log messages.
        """
        stale = self.search([
            ('definition_id', '=', definition.id),
            ('mk_instance_id', '=', mk_instance_id.id),
            ('mk_id', '!=', False),
            ('mk_id', 'not in', list(received_mk_ids)),
        ])
        if not stale:
            return

        removed, kept = [], []
        for entry in stale:
            label = entry._shopify_entry_label()
            try:
                entry.unlink()
                removed.append(label)
            except MarketplaceException:
                kept.append(label)

        if removed:
            mk_log_line_dict['success'].append({'log_message': _(
                "IMPORT METAOBJECT ENTRY: Removed %(names)s of metaobject %(definition)s from Odoo because they no longer exist in Shopify"
            ) % {'names': ', '.join(removed), 'definition': definition.display_name}})
        if kept:
            mk_log_line_dict['error'].append({'log_message': _(
                "IMPORT METAOBJECT ENTRY: Kept entries of metaobject %(definition)s that no longer exist in Shopify\n"
                "Reason: %(names)s are still used by other records\n"
                "How to fix:\n"
                "  • Remove each entry from where it is used, then delete it in Marketplaces > Shopify > Catalogs > Metaobject Entries"
            ) % {'definition': definition.display_name, 'names': ', '.join(kept)}})

    def import_shopify_entries_for_definitions(self, definitions, mk_instance_id, mk_log_line_dict):
        """Task: T9096 - Fetch the entries of several definitions with as few HTTP round trips as possible.

        Called right after Fetch Definitions, so one click brings back both the schema and
        the data instead of needing a separate Fetch Entries per definition.

        Shopify's metaobjects query requires exactly one type per call - there is no
        "entries of every type" query - but GraphQL aliasing lets several such calls share
        one HTTP request. Definitions are batched DEFINITION_BATCH_SIZE at a time, each
        fetching its first BATCH_PAGE_SIZE entries. A definition that has more than that
        falls back to the existing single-type paginator (import_shopify_metaobject_entries) to
        walk its remaining pages - the common case of a handful of entries per definition
        finishes entirely in the batch call and never needs that fallback.

        Args:
            definitions (recordset): Recordset of shopify.metaobject.definition.ts, all on
                mk_instance_id. Passed explicitly rather than read off the recordset:
                a Many2one field access on more than one record raises in Odoo.
            mk_instance_id (recordset): Recordset of mk.instance.
            mk_log_line_dict (dict): Dictionary to collect log messages.
        """
        if not definitions:
            return True
        mk_instance_id.connection_to_shopify()

        # needs_more_pages holds shopify.metaobject.definition.ts records (it is fed
        # `definition` singletons below and fed back into import_shopify_metaobject_entries,
        # which expects a definition) - built from the definition model explicitly, not
        # from self (this method lives on shopify.metaobject.entry.ts), since a bare
        # self.browse() here would silently be the wrong model entirely.
        definition_obj = self.env['shopify.metaobject.definition.ts']
        needs_more_pages = definition_obj.browse()
        definition_list = list(definitions)
        for start in range(0, len(definition_list), DEFINITION_BATCH_SIZE):
            batch = definition_list[start:start + DEFINITION_BATCH_SIZE]
            query = _build_shopify_metaobjects_batch_query(len(batch), BATCH_PAGE_SIZE)
            variables = {f"type{i}": definition.shopify_type for i, definition in enumerate(batch)}

            res = mk_instance_id.execute_graphql_query(query, variables=variables)
            if res and res.get('errors'):
                mk_log_line_dict['error'].append({'log_message': _(
                    "IMPORT METAOBJECT ENTRY: Could not fetch entries of metaobjects %(definitions)s from Shopify for instance (%(instance)s)\n"
                    "Reason: Shopify returned an error: %(error)s (Odoo fetches each of them on its own instead)"
                ) % {'definitions': ', '.join(d.display_name for d in batch), 'instance': mk_instance_id.name,
                     'error': res.get('errors')}})
                # Nothing trustworthy came back for this batch; let the per-definition
                # paginator fetch each of them properly instead of skipping them.
                needs_more_pages |= definition_obj.browse([d.id for d in batch])
                continue

            data = (res or {}).get('data') or {}
            for i, definition in enumerate(batch):
                alias_result = data.get(f"d{i}") or {}
                nodes = alias_result.get('nodes') or []
                received_mk_ids = set()
                for node in nodes:
                    gid = node.get('id')
                    if gid:
                        received_mk_ids.add(str(extract_numeric_id(gid)))
                if nodes:
                    self._create_or_update_shopify_metaobject_entries(nodes, mk_instance_id, mk_log_line_dict)

                if (alias_result.get('pageInfo') or {}).get('hasNextPage'):
                    # More than BATCH_PAGE_SIZE entries: only the paginator that walks every
                    # page can safely decide what is stale, so cleanup waits for it.
                    needs_more_pages |= definition
                else:
                    self._cleanup_stale_shopify_entries(definition, mk_instance_id, received_mk_ids, mk_log_line_dict)

        for definition in needs_more_pages:
            self.import_shopify_metaobject_entries(definition)
        return True

    def resolve_shopify_metaobject_gids(self, metaobject_gids, mk_instance_id, mk_log_line_dict=None):
        """Task: T9096 - Import the metaobject entries behind a list of GIDs, in batches.

        Called when a metafield value points at an entry Odoo has not seen yet.
        Deliberately a separate round trip: inlining the referenced metaobject in the
        product query would blow past Shopify's query-cost ceiling.

        Args:
            metaobject_gids (list): Shopify Metaobject GIDs.
            mk_instance_id (recordset): Recordset of mk.instance.
            mk_log_line_dict (dict, optional): Dictionary to collect log messages.
        Returns:
            recordset: The entries that exist in Odoo after the call.
        """
        if not metaobject_gids:
            return self.browse()
        if mk_log_line_dict is None:
            mk_log_line_dict = {'error': [], 'success': []}

        mk_instance_id.connection_to_shopify()
        unique_gids = list(dict.fromkeys(gid for gid in metaobject_gids if gid))
        for index in range(0, len(unique_gids), GID_CHUNK_SIZE):
            chunk = unique_gids[index:index + GID_CHUNK_SIZE]
            res = mk_instance_id.execute_graphql_query(GET_METAOBJECTS_BY_IDS, variables={"ids": chunk})
            if res and res.get('errors'):
                metafield = self.env.context.get('shopify_metafield')
                mk_log_line_dict['error'].append({'log_message': _(
                    "IMPORT METAOBJECT ENTRY: Could not fetch the linked metaobject entries for instance (%(instance)s)%(via)s\n"
                    "Reason: Shopify returned an error: %(error)s"
                ) % {'instance': mk_instance_id.name, 'error': res.get('errors'),
                     'via': _(" while importing metafield %s") % metafield if metafield else ''}})
                continue
            nodes = [node for node in (((res or {}).get('data') or {}).get('nodes') or []) if node]
            if nodes:
                self._create_or_update_shopify_metaobject_entries(nodes, mk_instance_id, mk_log_line_dict)

        return self.search([('mk_id', 'in', [str(extract_numeric_id(g)) for g in unique_gids]),
                            ('mk_instance_id', '=', mk_instance_id.id)])

    def _create_or_update_shopify_metaobject_entries(self, nodes, mk_instance_id, mk_log_line_dict):
        """Task: T9096 - Create or update entries and their value rows from Shopify nodes.

        Runs in two passes. Pass 1 creates every entry in the batch, so pass 2 can
        resolve references that point at entries from this same batch. Pass 2 resolves
        all reference ids with a handful of searches instead of one per value row.

        Args:
            nodes (list): Metaobject dictionaries returned by Shopify.
            mk_instance_id (recordset): Recordset of mk.instance.
            mk_log_line_dict (dict): Dictionary to collect log messages.
        """
        metafield = self.env.context.get('shopify_metafield')
        via = _(" while importing metafield %s") % metafield if metafield else ''
        if not mk_instance_id.enable_metaobject:
            # Backstop, not the primary UX: this is the one place every metaobject entry
            # write actually happens, reached both from the explicit Fetch actions (already
            # gated) and from auto-import triggered deep inside an ordinary
            # product/order/customer sync (resolve_shopify_metaobject_gids). Logged and skipped
            # rather than raised, since the caller here is normally mid-way through an
            # unrelated metafield/listing sync that must not be aborted over this.
            mk_log_line_dict['error'].append({'log_message': _(
                "IMPORT METAOBJECT ENTRY: Skipped saving metaobject entries for instance (%(instance)s)%(via)s\n"
                "Reason: Metaobject Functionality is turned off for this instance\n"
                "How to fix:\n"
                "  • Open the instance, go to the Metafields tab, and turn on Metaobject Functionality."
            ) % {'instance': mk_instance_id.name, 'via': via}})
            return False
        definition_obj = self.env['shopify.metaobject.definition.ts']
        value_obj = self.env['shopify.metaobject.entry.value.ts']
        entry_by_mk_id = {}

        definition_cache = self._resolve_shopify_definitions_for_nodes(nodes, mk_instance_id, mk_log_line_dict)

        # ---- pass 1: entries only -------------------------------------
        for node in nodes:
            shopify_type = node.get('type')
            definition = definition_cache.get(shopify_type)
            if not definition:
                mk_log_line_dict['error'].append({'log_message': _(
                    "IMPORT METAOBJECT ENTRY: Skipped entry %(entry)s of metaobject type %(type)s for instance (%(instance)s)%(via)s\n"
                    "Reason: Odoo does not have this metaobject and could not read it from Shopify\n"
                    "How to fix:\n"
                    "  • Click Fetch Definitions in Marketplaces > Shopify > Catalogs > Metaobjects"
                ) % {'entry': node.get('displayName') or node.get('handle'), 'type': shopify_type,
                     'instance': mk_instance_id.name, 'via': via}})
                continue

            mk_id = str(extract_numeric_id(node.get('id')))
            entry_vals = {
                'mk_instance_id': mk_instance_id.id,
                'definition_id': definition.id,
                'mk_id': mk_id,
                'handle': node.get('handle'),
                'display_name_ts': node.get('displayName'),
            }
            entry = self.search([('mk_id', '=', mk_id), ('mk_instance_id', '=', mk_instance_id.id)], limit=1)
            if entry:
                entry.write(entry_vals)
            else:
                entry = self.create(entry_vals)
            entry_by_mk_id[mk_id] = entry

        if not entry_by_mk_id:
            return True

        # ---- pass 2: values, with references resolved in bulk ----------
        reference_cache = self._build_shopify_reference_cache(nodes, definition_cache, mk_instance_id, mk_log_line_dict)

        for node in nodes:
            definition = definition_cache.get(node.get('type'))
            entry = entry_by_mk_id.get(str(extract_numeric_id(node.get('id'))))
            if not definition or not entry:
                continue

            fields_by_key = {f.key: f for f in definition.field_ids}
            values_by_key = {v.key: v for v in entry.value_ids}
            received_keys = set()
            for field_dict in node.get('fields') or []:
                key = field_dict.get('key')
                field_definition = fields_by_key.get(key)
                if not field_definition:
                    # Removed from the Shopify definition since the last Fetch Definitions.
                    continue
                value_record = values_by_key.get(key)
                if not value_record:
                    value_record = value_obj.create({'entry_id': entry.id, 'field_id': field_definition.id})
                try:
                    value_record._apply_shopify_value(field_dict.get('value'), reference_cache=reference_cache)
                    received_keys.add(key)
                except Exception as e:
                    mk_log_line_dict['error'].append({'log_message': _(
                        "IMPORT METAOBJECT ENTRY: Could not read the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: %(error)s (this value was left unchanged, the other values were imported)\n"
                        "How to fix:\n"
                        "  • Check the value of %(field)s on this entry in Shopify admin (Content > Metaobjects), then click Fetch Entries again"
                    ) % {'field': field_definition.name or key, 'entry': node.get('displayName') or node.get('handle'),
                         'definition': definition.display_name, 'instance': mk_instance_id.name, 'via': via,
                         'error': exception_message(e)}})

            # Shopify omits a field once it is cleared, so a value still sitting in Odoo is
            # stale. Same intent as wipe_unmatched in import_specific_type_metafield_from_shopify.
            stale_values = entry.value_ids.filtered(
                lambda v: v.key and v.is_supported and v.key not in received_keys)
            wiped = [v.field_id.name or v.key for v in stale_values if v.display_value]
            if stale_values:
                for stale in stale_values:
                    stale.write(stale._blank_shopify_value_vals())
            if wiped:
                mk_log_line_dict['success'].append({'log_message': _(
                    "IMPORT METAOBJECT ENTRY: Cleared the values of %(fields)s from entry %(entry)s (%(definition)s) in Odoo for instance (%(instance)s) because they are no longer set in Shopify"
                ) % {'fields': ', '.join(wiped), 'entry': node.get('displayName') or node.get('handle'),
                     'definition': definition.display_name, 'instance': mk_instance_id.name}})
        return True

    def _resolve_shopify_definitions_for_nodes(self, nodes, mk_instance_id, mk_log_line_dict=None):
        """Task: T9096 - Map every metaobject type in a batch to its local definition.

        A metafield can point at an entry whose definition was never imported, which
        would otherwise force the merchant to run Fetch Definitions and retry. When any
        type is unknown, OR a known type's entries carry a field key Odoo's copy of the
        schema does not have yet (a field was added to the definition in Shopify since the
        last Fetch Definitions, and this import ran before that was refreshed), the
        definitions are (re)fetched once for the whole batch and the lookup is retried. The
        context flag stops that from recursing.

        Args:
            nodes (list): Metaobject dictionaries returned by Shopify.
            mk_instance_id (recordset): Recordset of mk.instance.
        Returns:
            dict: {shopify_type: definition recordset}. Values may be empty recordsets
                when Shopify does not expose the definition to this app.
        """
        definition_obj = self.env['shopify.metaobject.definition.ts']
        shopify_types = {node.get('type') for node in nodes if node.get('type')}
        if not shopify_types:
            return {}

        definitions = definition_obj.search([
            ('shopify_type', 'in', list(shopify_types)), ('mk_instance_id', '=', mk_instance_id.id)])
        cache = {d.shopify_type: d for d in definitions}

        received_keys_by_type = {}
        for node in nodes:
            shopify_type = node.get('type')
            keys = {f.get('key') for f in node.get('fields') or [] if f.get('key')}
            if shopify_type and keys:
                received_keys_by_type.setdefault(shopify_type, set()).update(keys)

        missing_types = [t for t in shopify_types if t not in cache]
        stale_types = [
            shopify_type for shopify_type, definition in cache.items()
            if not received_keys_by_type.get(shopify_type, set()) <= set(definition.field_ids.mapped('key'))
        ]
        types_to_refresh = list(dict.fromkeys(missing_types + stale_types))

        if types_to_refresh and not self.env.context.get('skip_metaobject_definition_auto_import'):
            if mk_log_line_dict is None:
                mk_log_line_dict = {'error': [], 'success': []}
            metafield = self.env.context.get('shopify_metafield')
            via = _(" while importing metafield %s") % metafield if metafield else ''
            definitions_label = ', '.join(cache[t].display_name if t in cache else t for t in types_to_refresh)
            _logger.info("SHOPIFY METAOBJECT: definition(s) %s unknown or out of date, fetching them from Shopify.",
                         ', '.join(types_to_refresh))
            # Fetch directly rather than through action_fetch_shopify_metaobject_definitions, so any
            # failure lands in the caller's log instead of a separate mk.log record.
            try:
                # Always a full-instance fetch (FETCH_METAOBJECT_DEFINITIONS has no type
                # filter), so this refreshes every type's schema in one call regardless of how
                # many triggered it; its completeness is irrelevant here - stale definition
                # cleanup only ever runs from action_fetch_shopify_metaobject_definitions.
                definitions, _is_complete = definition_obj.with_context(
                    skip_metaobject_definition_auto_import=True,
                )._fetch_shopify_metaobject_definitions(mk_instance_id, mk_log_line_dict)
                if definitions:
                    definition_obj._create_or_update_shopify_metaobject_definitions(definitions, mk_instance_id)
                else:
                    mk_log_line_dict['error'].append({'log_message': _(
                        "IMPORT METAOBJECT DEFINITION: Could not fetch the definition (%(definitions)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: Shopify returned no metaobject definitions"
                    ) % {'definitions': definitions_label, 'instance': mk_instance_id.name, 'via': via}})
            except Exception as e:
                mk_log_line_dict['error'].append({'log_message': _(
                    "IMPORT METAOBJECT DEFINITION: Could not fetch the definition (%(definitions)s) for instance (%(instance)s)%(via)s\n"
                    "Reason: %(error)s"
                ) % {'definitions': definitions_label, 'instance': mk_instance_id.name, 'via': via,
                     'error': exception_message(e)}})

            for definition in definition_obj.search([
                    ('shopify_type', 'in', types_to_refresh), ('mk_instance_id', '=', mk_instance_id.id)]):
                cache[definition.shopify_type] = definition

        for shopify_type in shopify_types:
            cache.setdefault(shopify_type, definition_obj.browse())
        return cache

    def _log_shopify_metaobject_reference(self, mk_log_line_dict, level, origins_for_bucket, mk_ids, message):
        """Task: T9096 - Append one log line per (entry, field) pair that referenced one of mk_ids.

        A single reference id can be reached from more than one (entry, field) - e.g. the
        same missing product referenced by two different entries - so this reports every
        occurrence, not just the id once.

        Args:
            mk_log_line_dict (dict): Dictionary to collect log messages.
            level ('success' | 'error'): Which bucket of mk_log_line_dict to append to.
            origins_for_bucket (dict): {mk_id: [{'entry', 'field', 'definition', 'instance'}, ...]}.
            mk_ids (iterable): Shopify ids to report.
            message (str): Already-translated template with %(entry)s, %(field)s, %(definition)s,
                %(instance)s, %(mk_id)s and %(via)s.
        """
        metafield = self.env.context.get('shopify_metafield')
        via = _(" while importing metafield %s") % metafield if metafield else ''
        for mk_id in sorted(mk_ids):
            for origin in origins_for_bucket[mk_id]:
                mk_log_line_dict[level].append({'log_message': message % {**origin, 'mk_id': mk_id, 'via': via}})

    def _build_shopify_reference_cache(self, nodes, definition_cache, mk_instance_id, mk_log_line_dict=None):
        """Task: T9096 - Resolve every reference id in a batch with one search per reference kind.

        Without this, a 5000-entry import with two reference fields each would issue
        10000 individual searches.

        Mirrors the metafield-level reference handling in
        marketplace_instance.set_shopify_reference_metafield_value: product and nested
        metaobject references are auto-imported (bounded by
        skip_metafield_reference_auto_import, same context flag, not a new depth counter -
        past that one hop, they are reported exactly like a reference type that is never
        auto-imported, not silently dropped). Variant references are never auto-imported and
        are always only reported, since that is the existing behaviour for variant_reference
        metafields too. Every outcome - auto-imported, blocked by depth, or variant's
        by-design "never" - gets its own log line; nothing here fails silently.

        Args:
            nodes (list): Metaobject dictionaries returned by Shopify.
            definition_cache (dict): {shopify_type: definition recordset}.
            mk_instance_id (recordset): Recordset of mk.instance.
            mk_log_line_dict (dict, optional): Dictionary to collect log messages.
        Returns:
            dict: {'product': {mk_id: odoo_id}, 'variant': {...}, 'entry': {...}}
        """
        if mk_log_line_dict is None:
            mk_log_line_dict = {'error': [], 'success': []}

        value_obj = self.env['shopify.metaobject.entry.value.ts']
        buckets = {bucket: set() for bucket in value_obj._shopify_reference_buckets()}
        # {bucket: {mk_id: [{'entry', 'field', 'definition', 'instance'}, ...]}}, for readable "missing" logs.
        origins = {bucket: {} for bucket in value_obj._shopify_reference_buckets()}

        for node in nodes:
            definition = definition_cache.get(node.get('type'))
            if not definition:
                continue
            fields_by_key = {f.key: f for f in definition.field_ids}
            for field_dict in node.get('fields') or []:
                key = field_dict.get('key')
                field_definition = fields_by_key.get(key)
                field_type = field_definition.field_type if field_definition else ''
                if '_reference' not in field_type:
                    continue
                bucket = value_obj._shopify_reference_bucket_for_type(field_type)
                if not bucket:
                    continue
                raw = field_dict.get('value')
                if not raw:
                    continue
                if field_type.startswith('list.'):
                    gid_list = value_obj._safe_shopify_json_loads(raw) or []
                else:
                    gid_list = [raw]
                for gid in gid_list:
                    if not gid:
                        continue
                    mk_id = str(extract_numeric_id(gid))
                    buckets[bucket].add(mk_id)
                    origins[bucket].setdefault(mk_id, []).append({
                        'entry': node.get('displayName') or node.get('handle'), 'field': field_definition.name or key,
                        'definition': definition.display_name, 'instance': mk_instance_id.name})

        skip_auto_import = self.env.context.get('skip_metafield_reference_auto_import')
        cache = {}
        for bucket, mk_ids in buckets.items():
            cache[bucket] = {}
            if not mk_ids:
                continue
            model_name, target = value_obj._shopify_reference_buckets()[bucket]
            domain = [('mk_id', 'in', list(mk_ids)), ('mk_instance_id', '=', mk_instance_id.id)]
            records = self.env[model_name].search(domain)
            missing = mk_ids - set(records.mapped('mk_id'))

            if missing and bucket == 'product':
                if skip_auto_import:
                    self._log_shopify_metaobject_reference(mk_log_line_dict, 'error', origins[bucket], missing, _(
                        "IMPORT METAOBJECT ENTRY: Skipped the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: it links to Shopify product %(mk_id)s, which is not in Odoo\n"
                        "How to fix:\n"
                        "  • Import this product into Odoo, then click Fetch Entries again"))
                else:
                    # Products referenced from inside a metaobject get auto-imported, the
                    # same way set_shopify_reference_metafield_value does for a
                    # product_reference metafield.
                    mk_instance_id._import_missing_shopify_metafield_references(
                        [f"gid://shopify/Product/{mk_id}" for mk_id in missing],
                        mk_log_id=self.env.context.get('mk_log_id'), mk_log_line_dict=mk_log_line_dict)
                    records = self.env[model_name].search(domain)
                    still_missing = mk_ids - set(records.mapped('mk_id'))
                    self._log_shopify_metaobject_reference(
                        mk_log_line_dict, 'success', origins[bucket], missing - still_missing, _(
                            "IMPORT METAOBJECT ENTRY: Imported the linked product (Shopify ID %(mk_id)s) into Odoo because field %(field)s of entry %(entry)s (%(definition)s) links to it, for instance (%(instance)s)%(via)s"))
                    self._log_shopify_metaobject_reference(mk_log_line_dict, 'error', origins[bucket], still_missing, _(
                        "IMPORT METAOBJECT ENTRY: Skipped the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: it links to Shopify product %(mk_id)s, which Odoo could not import from Shopify\n"
                        "How to fix:\n"
                        "  • Check the product exists in Shopify, then import it into Odoo and click Fetch Entries again"))
                    missing = still_missing

            if missing and bucket == 'entry':
                if skip_auto_import:
                    self._log_shopify_metaobject_reference(mk_log_line_dict, 'error', origins[bucket], missing, _(
                        "IMPORT METAOBJECT ENTRY: Skipped the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: it links to Shopify metaobject entry %(mk_id)s, which is not in Odoo\n"
                        "How to fix:\n"
                        "  • Click Fetch Definitions in Marketplaces > Shopify > Catalogs > Metaobjects"))
                else:
                    # Nested metaobject_reference: auto-import the referenced entry, bounded
                    # by the same context flag as every other auto-import on this path so a
                    # cycle between two metaobject types cannot recurse past one extra hop.
                    self.with_context(skip_metafield_reference_auto_import=True).resolve_shopify_metaobject_gids(
                        [f"gid://shopify/Metaobject/{mk_id}" for mk_id in missing],
                        mk_instance_id, mk_log_line_dict=mk_log_line_dict)
                    records = self.env[model_name].search(domain)
                    still_missing = mk_ids - set(records.mapped('mk_id'))
                    self._log_shopify_metaobject_reference(
                        mk_log_line_dict, 'success', origins[bucket], missing - still_missing, _(
                            "IMPORT METAOBJECT ENTRY: Fetched the linked metaobject entry (Shopify ID %(mk_id)s) because field %(field)s of entry %(entry)s (%(definition)s) links to it, for instance (%(instance)s)%(via)s"))
                    self._log_shopify_metaobject_reference(mk_log_line_dict, 'error', origins[bucket], still_missing, _(
                        "IMPORT METAOBJECT ENTRY: Skipped the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                        "Reason: it links to Shopify metaobject entry %(mk_id)s, which Odoo could not fetch from Shopify\n"
                        "How to fix:\n"
                        "  • Check the entry exists in Shopify admin (Content > Metaobjects), then click Fetch Definitions in Marketplaces > Shopify > Catalogs > Metaobjects"))
                    missing = still_missing

            if missing and bucket == 'variant':
                # Mirrors variant_reference at the metafield level: never auto-imported,
                # only reported, because a listing item has no standalone "import just this
                # variant" entry point the way a product or metaobject entry does.
                self._log_shopify_metaobject_reference(mk_log_line_dict, 'error', origins[bucket], missing, _(
                    "IMPORT METAOBJECT ENTRY: Skipped the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)%(via)s\n"
                    "Reason: it links to Shopify variant %(mk_id)s, which is not in Odoo\n"
                    "How to fix:\n"
                    "  • Import the product that owns this variant into Odoo, then click Fetch Entries again"))

            for record in records:
                cache[bucket][record.mk_id] = (record if target is None else record[target]).id
        return cache

    # ==================================================================
    # EXPORT
    # ==================================================================
    def handle_deleted_in_shopify(self, mk_log_line_dict=None, owner_label='listing', mk_record=None, metafield_key=''):
        """Task: T9096 - Handle metaobject entries in Odoo when deleted in Shopify."""
        record_name = mk_record.display_name if mk_record else ''
        record_mk_id = mk_record.mk_id if mk_record else ''

        for entry in self:
            entry_label = entry._shopify_entry_label()
            log_vals = {'entry': entry_label, 'definition': entry.definition_id.name, 'metafield': metafield_key,
                        'owner_label': owner_label, 'record_name': record_name, 'record_mk_id': record_mk_id}
            try:
                # Bypass the manual block and force the database deletion
                entry.with_context(force_shopify_delete=True).unlink()

                if mk_log_line_dict is not None:
                    mk_log_line_dict['success'].append({'log_message': _(
                        "UPDATE LISTING: Metafield %(metafield)s on %(owner_label)s %(record_name)s (%(record_mk_id)s) was not updated\n"
                        "Reason: its entry %(entry)s (%(definition)s) was deleted in Shopify, so Odoo removed it\n"
                        "How to fix:\n"
                        "  • Run the update again"
                    ) % log_vals})
            except Exception:
                # Tell the user exactly which metafield on which product has the stale data
                if mk_log_line_dict is not None:
                    mk_log_line_dict['error'].append({'log_message': _(
                        "UPDATE LISTING: Metafield %(metafield)s on %(owner_label)s %(record_name)s (%(record_mk_id)s) was not updated\n"
                        "Reason: its entry %(entry)s (%(definition)s) was deleted in Shopify, but it is still selected in Odoo\n"
                        "How to fix:\n"
                        "  • Remove %(entry)s from %(metafield)s: open the product of this %(owner_label)s (Marketplaces > Products > Products), go to the Shopify Metaobject Fields tab, then run the update again"
                    ) % log_vals})

    def action_push_to_shopify(self):
        """Task: T9096 - Create or update this entry in Shopify."""
        self.ensure_one()
        mk_log_line_dict = {'error': [], 'success': []}
        if not self.mk_instance_id.enable_metaobject:
            # Show the same "turned off" message as a popup instead of leaving only a log line.
            self.push_to_shopify(mk_log_line_dict=mk_log_line_dict)
            raise MarketplaceException(mk_log_line_dict['error'][0]['log_message'])
        mk_log_id = self.env['mk.log'].create_update_log(mk_instance_id=self.mk_instance_id, operation_type='export')
        self.push_to_shopify(mk_log_line_dict=mk_log_line_dict)
        self.env['mk.log'].create_update_log(mk_log_id=mk_log_id, mk_instance_id=self.mk_instance_id,
                                             operation_type='export', mk_log_line_dict=mk_log_line_dict)
        if not mk_log_id.log_line_ids:
            mk_log_id.unlink()
        return True

    def push_to_shopify(self, mk_log_line_dict=None):
        """Task: T9096 - Push the entry to Shopify, creating it when it has no Shopify id yet.

        Args:
            mk_log_line_dict (dict, optional): Dictionary to collect log messages.
        Returns:
            bool: True when Shopify accepted the write.
        """
        self.ensure_one()
        if mk_log_line_dict is None:
            mk_log_line_dict = {'error': [], 'success': []}

        if not self.mk_instance_id.enable_metaobject:
            mk_log_line_dict['error'].append({'log_message': _(
                "EXPORT METAOBJECT ENTRY: Cannot sync entry %(entry)s (%(definition)s) to Shopify for instance (%(instance)s)\n"
                "Reason: Metaobject Functionality is turned off for this instance\n"
                "How to fix:\n"
                "  • Go to Marketplaces > Configuration > Instance, open the instance, go to the Metafields tab, and turn on Metaobject Functionality."
            ) % {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                 'instance': self.mk_instance_id.name}})
            return False

        if not self.definition_id.is_app_writable:
            mk_log_line_dict['error'].append({'log_message': _(
                "EXPORT METAOBJECT ENTRY: Cannot sync entry %(entry)s (%(definition)s) to Shopify for instance (%(instance)s)\n"
                "Reason: Shopify only lets Shopify staff add or change entries of this metaobject\n"
                "How to fix:\n"
                "  • Add or change the entry in Shopify admin (Content > Metaobjects), then go to Marketplaces > Shopify > Catalogs > Metaobjects, open the metaobject and click Fetch Entries"
            ) % {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                 'instance': self.mk_instance_id.name}})
            return False

        mk_instance_id = self.mk_instance_id
        mk_instance_id.connection_to_shopify()
        payload_fields = self._prepare_shopify_metaobject_fields_payload(mk_log_line_dict)
        if not payload_fields:
            mk_log_line_dict['error'].append({'log_message': _(
                "EXPORT METAOBJECT ENTRY: Nothing synced for entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                "Reason: every field is empty or links to records that are not synced to Shopify yet\n"
                "How to fix:\n"
                "  • Go to Marketplaces > Shopify > Catalogs > Metaobject Entries, open the entry, fill in a value in the Values tab and sync the linked records, then click Sync to Shopify"
            ) % {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                 'instance': mk_instance_id.name}})
            return False

        if self.mk_id:
            query = UPDATE_METAOBJECT
            variables = {"id": f"gid://shopify/Metaobject/{self.mk_id}",
                         "metaobject": {"fields": payload_fields}}
            result_key = 'metaobjectUpdate'
        else:
            metaobject_input = {"type": self.definition_id.shopify_type, "fields": payload_fields}
            if self.handle:
                metaobject_input['handle'] = self.handle
            query = CREATE_METAOBJECT
            variables = {"metaobject": metaobject_input}
            result_key = 'metaobjectCreate'

        res = mk_instance_id.execute_graphql_query(query, variables=variables)
        result = ((res or {}).get('data') or {}).get(result_key) or {}
        user_errors = result.get('userErrors') or []

        # metafieldsSet drops the rejected entries and re-issues the mutation once
        # (_update_shopify_metafield_values). Do the same so one bad field does not cost
        # the whole entry.
        if user_errors:
            failed_indices = {idx for idx in (self._shopify_field_error_index(e) for e in user_errors)
                              if idx is not None and idx < len(payload_fields)}
            if failed_indices:
                for index in sorted(failed_indices):
                    error = next((e for e in user_errors if self._shopify_field_error_index(e) == index), {})
                    field_key = payload_fields[index].get('key')
                    field_name = self.definition_id.field_ids.filtered(lambda f: f.key == field_key)[:1].name or field_key
                    mk_log_line_dict['error'].append({'log_message': _(
                        "EXPORT METAOBJECT ENTRY: Shopify rejected the value of field %(field)s of entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                        "Reason: %(message)s (code: %(code)s), the other values were synced\n"
                        "How to fix:\n"
                        "  • Go to Marketplaces > Shopify > Catalogs > Metaobject Entries, open the entry, correct %(field)s in the Values tab, then click Sync to Shopify"
                    ) % {'field': field_name, 'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                         'instance': mk_instance_id.name, 'message': error.get('message'), 'code': error.get('code')}})
                cleaned = [f for i, f in enumerate(payload_fields) if i not in failed_indices]
                if cleaned:
                    variables['metaobject'] = dict(variables['metaobject'], fields=cleaned)
                    res = mk_instance_id.execute_graphql_query(query, variables=variables)
                    result = ((res or {}).get('data') or {}).get(result_key) or {}
                    user_errors = result.get('userErrors') or []
                else:
                    user_errors = []
                    result = {}

        if user_errors:
            for error in user_errors:
                mk_log_line_dict['error'].append({'log_message': _(
                    "EXPORT METAOBJECT ENTRY: Shopify rejected entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                    "Reason: %(message)s (field: %(field)s, code: %(code)s)"
                ) % {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                     'instance': mk_instance_id.name, 'message': error.get('message'),
                     'field': error.get('field'), 'code': error.get('code')}})
            return False

        metaobject = result.get('metaobject') or {}
        if metaobject:
            self.write({
                'mk_id': str(extract_numeric_id(metaobject.get('id'))),
                'handle': metaobject.get('handle'),
                'display_name_ts': metaobject.get('displayName') or self.display_name_ts,
            })
        mk_log_line_dict['success'].append({'log_message': _(
            "EXPORT METAOBJECT ENTRY: Entry %(entry)s (%(definition)s) was synced to Shopify for instance (%(instance)s)"
        ) % {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
             'instance': mk_instance_id.name}})
        return True

    def _shopify_field_error_index(self, error):
        """Task: T9096 - Index into the fields list that a Shopify userError points at, or None.

        Shopify returns paths such as ['metaobject', 'fields', '2', 'value'].
        """
        for part in error.get('field') or []:
            if isinstance(part, str) and part.isdigit():
                return int(part)
            if isinstance(part, int):
                return part
        return None

    def _prepare_shopify_metaobject_fields_payload(self, mk_log_line_dict=None):
        """Task: T9096 - Build the `fields` list for metaobjectCreate / metaobjectUpdate.

        A field whose references are not in Shopify yet is SKIPPED and the reason logged,
        so the rest of the entry still exports. This mirrors how metafields behave in
        prepare_shopify_reference_value_for_update. Because Shopify patches the entry,
        a skipped field simply keeps its current Shopify value instead of being cleared.

        Args:
            mk_log_line_dict (dict, optional): Dictionary to collect log messages.
        Returns:
            list: [{'key': str, 'value': str}, ...]
        """
        self.ensure_one()
        payload = []
        for value_record in self.value_ids:
            if not value_record.key:
                continue
            # Never send a type the connector cannot convert: omitting it from a patch
            # update leaves the merchant's Shopify value exactly as it was.
            if not value_record.is_supported:
                continue
            skip_reason = value_record._export_skip_reason()
            if skip_reason:
                if mk_log_line_dict is not None:
                    mk_log_line_dict['error'].append({'log_message': skip_reason})
                continue
            shopify_value = value_record._to_shopify_value(mk_log_line_dict=mk_log_line_dict)
            payload.append({'key': value_record.key, 'value': '' if shopify_value in (False, None) else shopify_value})
        return payload

    # ==================================================================
    # DELETE
    # ==================================================================
    def action_delete_from_shopify(self):
        """Task: T9096 - Remove this entry from Shopify (if it was ever pushed) and then from Odoo."""
        self.ensure_one()
        mk_instance = self.mk_instance_id
        mk_log_line_dict = {'error': [], 'success': []}
        if not mk_instance.enable_metaobject:
            # Show the same "turned off" message as a popup instead of leaving only a log line.
            self.delete_from_shopify(mk_log_line_dict=mk_log_line_dict)
            raise MarketplaceException(mk_log_line_dict['error'][0]['log_message'])
        mk_log_id = self.env['mk.log'].create_update_log(mk_instance_id=mk_instance, operation_type='export')
        is_deleted = self.delete_from_shopify(mk_log_line_dict=mk_log_line_dict)
        self.env['mk.log'].create_update_log(mk_log_id=mk_log_id, mk_instance_id=mk_instance,
                                             operation_type='export', mk_log_line_dict=mk_log_line_dict)
        if not mk_log_id.log_line_ids:
            mk_log_id.unlink()

        if is_deleted:
            action = self.env['ir.actions.act_window']._for_xml_id('shopify.action_shopify_metaobject_entries')
            return action
        return True

    def delete_from_shopify(self, mk_log_line_dict=None):
        """Task: T9096 - Delete this entry in Shopify, when it has one, then remove the Odoo record.

        The reference check runs BEFORE the Shopify call, not after: deleting in Shopify
        and then finding the local unlink blocked would leave Odoo pointing at a Shopify id
        that no longer exists.

        Args:
            mk_log_line_dict (dict, optional): Dictionary to collect log messages.
        Returns:
            bool: True once removed from Shopify (if applicable) and from Odoo.
        """
        self.ensure_one()
        if mk_log_line_dict is None:
            mk_log_line_dict = {'error': [], 'success': []}
        # Read before the record is deleted: the success line below is written after unlink().
        log_vals = {'entry': self._shopify_entry_label(), 'definition': self.definition_id.name,
                    'instance': self.mk_instance_id.name}

        if not self.mk_instance_id.enable_metaobject:
            mk_log_line_dict['error'].append({'log_message': _(
                "UPDATE METAOBJECT ENTRY: Cannot delete entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                "Reason: Metaobject Functionality is turned off for this instance\n"
                "How to fix:\n"
                "  • Go to Marketplaces > Configuration > Instance, open the instance, go to the Metafields tab, and turn on Metaobject Functionality."
            ) % log_vals})
            return False

        if not self.definition_id.is_app_writable:
            mk_log_line_dict['error'].append({'log_message': _(
                "UPDATE METAOBJECT ENTRY: Cannot delete entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                "Reason: Shopify only lets Shopify staff delete entries of this metaobject\n"
                "How to fix:\n"
                "  • Delete the entry in Shopify admin (Content > Metaobjects), then go to Marketplaces > Shopify > Catalogs > Metaobjects, open the metaobject and click Fetch Entries"
            ) % log_vals})
            return False

        usages = self._is_shopify_entry_referenced(with_usages=True)
        if usages:
            mk_log_line_dict['error'].append({'log_message': _(
                "UPDATE METAOBJECT ENTRY: Cannot delete entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                "Reason: it is still used by these records:\n"
                "%(usages)s\n"
                "How to fix:\n"
                "  • Open each record above (a product: Marketplaces > Products > Products, tab Shopify Metaobject Fields), remove the entry, then delete it again"
            ) % {**log_vals, 'usages': "\n".join(f"  • {usage}" for usage in usages)}})
            return False

        if self.mk_id:
            mk_instance_id = self.mk_instance_id
            mk_instance_id.connection_to_shopify()
            res = mk_instance_id.execute_graphql_query(
                DELETE_METAOBJECT, variables={"id": f"gid://shopify/Metaobject/{self.mk_id}"})
            result = ((res or {}).get('data') or {}).get('metaobjectDelete') or {}
            user_errors = result.get('userErrors') or []
            if user_errors:
                for error in user_errors:
                    mk_log_line_dict['error'].append({'log_message': _(
                        "UPDATE METAOBJECT ENTRY: Shopify rejected deleting entry %(entry)s (%(definition)s) for instance (%(instance)s)\n"
                        "Reason: %(message)s (code: %(code)s)"
                    ) % {**log_vals, 'message': error.get('message'), 'code': error.get('code')}})
                return False

        try:
            self.unlink()
        except MarketplaceException as e:
            mk_log_line_dict['error'].append({'log_message': exception_message(e)})
            return False

        mk_log_line_dict['success'].append({'log_message': _(
            "UPDATE METAOBJECT ENTRY: Entry %(entry)s (%(definition)s) was deleted from Shopify and Odoo for instance (%(instance)s)"
        ) % log_vals})
        return True
