from . import shopify_backend
from . import shopify_binding
from . import shopify_sync_log
from . import shopify_webhook_log
from . import shopify_product_binding
from . import shopify_variant_binding
from . import shopify_customer_binding
from . import shopify_order_binding
from . import shopify_inventory_binding
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import shopify_field_mapping
from . import shopify_reconciliation
from . import stock_picking
from . import stock_move
from . import shopify_promoter
from . import shopify_discount_code
from . import shopify_discount_usage
from . import shopify_collection_binding
