# Part of Adams Shopify Connector. See LICENSE file for full copyright and licensing details.
{
    'name': 'Adams Shopify Connector',
    'version': '19.0.1.0.0',
    'category': 'Sales/Sales',
    'summary': 'Sync products, orders, customers and inventory with Shopify',
    'description': 'Bidirectional Shopify ↔ Odoo connector built on Shopify GraphQL Admin API 2026-01.',
    'author': 'Adams',
    'website': 'https://github.com/adamsodoo/adams',
    'support': 'support@adamsodoo.com',
    'license': 'OPL-1',
    'price': 0,
    'currency': 'USD',
    'depends': [
        'adams_base',
        'product',
        'sale_management',
        'stock',
        'contacts',
        'mail',
        'account',
    ],
    'external_dependencies': {
        'python': ['requests'],
    },
    'data': [
        'security/shopify_security.xml',
        'security/ir.model.access.csv',
        'data/shopify_cron.xml',
        'views/shopify_backend_views.xml',
        'views/shopify_product_binding_views.xml',
        'views/shopify_customer_binding_views.xml',
        'views/shopify_order_binding_views.xml',
        'views/shopify_inventory_binding_views.xml',
        'views/shopify_sync_log_views.xml',
        'views/shopify_webhook_log_views.xml',
        'views/shopify_dashboard_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'wizards/shopify_sync_wizard_views.xml',
        'wizards/shopify_import_wizard_views.xml',
        'wizards/shopify_bulk_retry_wizard_views.xml',
        'views/shopify_field_mapping_views.xml',
        'views/shopify_promoter_views.xml',
        'views/shopify_discount_code_views.xml',
        'views/shopify_discount_usage_views.xml',
        'views/shopify_collection_binding_views.xml',
        'views/shopify_refund_binding_views.xml',
        'views/shopify_payment_gateway_views.xml',
        'views/shopify_tax_mapping_views.xml',
        'views/shopify_metafield_views.xml',
        'views/shopify_location_views.xml',
        'views/shopify_customer_tag_views.xml',
        'views/shopify_gift_card_views.xml',
        'views/shopify_import_job_views.xml',
        'views/shopify_payout_views.xml',
        'views/shopify_abandoned_cart_views.xml',
        'wizards/shopify_onboarding_wizard_views.xml',
        'wizards/shopify_bulk_export_wizard_views.xml',
        'wizards/shopify_demo_data_wizard_views.xml',
        'views/shopify_menu.xml',
    ],
    'demo': [],
    'assets': {},
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
}
