# Part of Shopify Connector Pro Ultimate Edition.
# Copyright (C) 2026 Qamah Solutions — Managed by Odoo Partner Ahmed Saad (ahmedsaad@tech-oriented.com)
# See LICENSE file for full copyright and licensing details.
{
    'name': 'Shopify Connector Pro Ultimate Edition',
    'version': '19.0.1.1.0',
    'category': 'Sales/Sales',
    'summary': 'Production-grade bidirectional Shopify <> Odoo connector with manager dashboard: products, orders, customers, inventory, fulfillments, refunds, payouts, promoters, webhooks, and more.',
    'description': 'Shopify Connector Pro Ultimate Edition — enterprise-grade bidirectional Shopify <> Odoo 19 connector built on Shopify GraphQL Admin API 2026-01 with integrated manager dashboard, KPI analytics, and delivery tracking.',
    'author': 'Qamah Solutions',
    'maintainer': 'Qamah Solutions — Managed by Odoo Partner Ahmed Saad',
    'website': 'https://qamah.odoo.com',
    'support': 'ahmedsaad@tech-oriented.com',
    'license': 'OPL-1',
    'price': 1800.00,
    'currency': 'USD',
    'depends': [
        'product',
        'sale_management',
        'stock',
        'contacts',
        'mail',
        'account',
    ],
    'external_dependencies': {
        'python': ['requests', 'cryptography'],
    },
    'data': [
        'security/shopify_security.xml',
        'security/ir.model.access.csv',
        'data/shopify_cron.xml',
        'views/shopify_backend_views.xml',
        'views/shopify_product_binding_views.xml',
        'views/shopify_customer_binding_views.xml',
        'views/shopify_order_binding_views.xml',
        'views/shopify_inventory_binding_views.xml',
        'views/shopify_sync_log_views.xml',
        'views/shopify_webhook_log_views.xml',
        'views/shopify_dashboard_views.xml',
        'views/manager_dashboard_action.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'wizards/shopify_sync_wizard_views.xml',
        'wizards/shopify_import_wizard_views.xml',
        'wizards/shopify_bulk_retry_wizard_views.xml',
        'views/shopify_field_mapping_views.xml',
        'views/shopify_promoter_views.xml',
        'views/shopify_discount_code_views.xml',
        'views/shopify_discount_usage_views.xml',
        'views/shopify_collection_binding_views.xml',
        'views/shopify_refund_binding_views.xml',
        'views/shopify_payment_gateway_views.xml',
        'views/shopify_tax_mapping_views.xml',
        'views/shopify_metafield_views.xml',
        'views/shopify_location_views.xml',
        'views/shopify_customer_tag_views.xml',
        'views/shopify_gift_card_views.xml',
        'views/shopify_import_job_views.xml',
        'views/shopify_payout_views.xml',
        'views/shopify_abandoned_cart_views.xml',
        'wizards/shopify_onboarding_wizard_views.xml',
        'data/shopify_onboarding_todo.xml',
        'wizards/shopify_bulk_export_wizard_views.xml',
        'wizards/shopify_demo_data_wizard_views.xml',
        'views/shopify_menu.xml',
    ],
    'demo': [],
    'assets': {
        'web.assets_backend': [
            'shopify_connector_pro/static/src/scss/manager_dashboard.scss',
            'shopify_connector_pro/static/src/js/manager_dashboard/**/*.js',
            'shopify_connector_pro/static/src/xml/manager_dashboard/**/*.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': [
        'static/description/icon.png',
        'static/description/screenshot_01_dashboard.png',
        'static/description/screenshot_02_backend_form.png',
        'static/description/screenshot_03_manager_dashboard.png',
        'static/description/screenshot_04_order_bindings.png',
        'static/description/screenshot_05_onboarding.png',
    ],
}
